FROM rust:1.85.1-slim

RUN apt-get update && apt-get install -y git curl wget unzip jq sudo

# Create the user with home directory and bash shell
RUN useradd -m -s /bin/bash verususer && \
    echo "verususer ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the new user
USER verususer
WORKDIR /home/verususer

# Download and unpack verus
RUN URL=$(curl -s https://api.github.com/repos/verus-lang/verus/releases/latest \
    | jq -r '.assets[] | select(.name | test("x86-linux\\.zip$")) | .browser_download_url') && \
    echo "Downloading $URL" && \
    wget "$URL" -O verus.zip && \
    unzip verus.zip && \
    chmod +x ~/verus-*/verus

# Install verus 
RUN sudo cp -r ~/verus-x86-linux /opt/verus; \
    sudo ln -s /opt/verus/verus /usr/local/bin/verus
    
# Clean up the build directory
RUN rm -rf ~/verus.zip ~/verus-x86-linux