FROM rust:1.82.0-slim

RUN apt-get update && apt-get install -y git curl wget unzip jq sudo

# Create the user with home directory and bash shell
RUN useradd -m -s /bin/bash verususer && \
    echo "verususer ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Switch to the new user
USER verususer
WORKDIR /home/verususer

# Download and install Verus
RUN URL=$(curl -s https://api.github.com/repos/verus-lang/verus/releases/latest \
    | jq -r '.assets[] | select(.name | test("x86-linux\\.zip$")) | .browser_download_url') && \
    echo "Downloading $URL" && \
    wget "$URL" -O verus.zip && \
    unzip verus.zip && \
    chmod +x ~/verus-*/verus && \
    mv verus-x86-linux verus && \ 
    rm -rf verus.zip verus-*  

ENV PATH="~/verus:${PATH}"


